const art=document.querySelector('.art');
const pause=document.querySelector('.animation-toggle');
pause.addEventListener('click',()=>{const paused=art.classList.toggle('paused');pause.setAttribute('aria-pressed',String(paused));pause.textContent=paused?'Reanudar animación':'Pausar animación';});
const dose=document.getElementById('confirm-dose');
const status=document.getElementById('dose-status');
const progress=document.getElementById('demo-progress');
function updateDemo(taken){dose.disabled=taken;dose.textContent=taken?'Toma confirmada ✓':'Ya me la tomé';status.textContent=taken?'¡Listo! Confirmaste la dosis de ejemplo.':'Una dosis pendiente en esta demostración.';progress.value=taken?1:0;document.getElementById('progress-count').textContent=taken?'1 de 1':'0 de 1';document.getElementById('progress-text').textContent=taken?'Completaste esta demostración. Puedes reiniciarla.':'Comienza confirmando la toma de ejemplo.';}
dose.addEventListener('click',()=>updateDemo(true));document.getElementById('reset-demo').addEventListener('click',()=>updateDemo(false));
const steps=[['Instala CUIDEXA','Descarga la APK en tu teléfono Android y abre el archivo para instalarla. Si tienes una versión anterior, conserva tus datos y comprueba que Android permita actualizarla.'],['Organiza tu receta','En la aplicación, registra el medicamento y sus horarios tal como aparecen en tu receta. Revisa los datos antes de guardar el tratamiento.'],['Confirma cada toma','Cuando tomes una dosis, márcala en la aplicación y revisa tu próxima toma. Comprueba los permisos de notificaciones de tu teléfono.']];
document.querySelectorAll('[data-step]').forEach(button=>button.addEventListener('click',()=>{const i=Number(button.dataset.step);document.querySelectorAll('[data-step]').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});document.getElementById('step-number').textContent='0'+(i+1);document.getElementById('step-title').textContent=steps[i][0];document.getElementById('step-description').textContent=steps[i][1];}));
document.getElementById('report-form').addEventListener('submit',event=>{event.preventDefault();const message=document.getElementById('report-message').value.trim();if(message.length<10){document.getElementById('report-status').textContent='Escribe al menos 10 caracteres para preparar el reporte.';return;}const text=['Reporte de CUIDEXA',new Date().toISOString(),'Tipo: '+document.getElementById('report-type').value,'Área: '+document.getElementById('report-area').value,'',message].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='CUIDEXA-reporte.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);document.getElementById('report-status').textContent='Reporte preparado. Comparte el archivo en esta conversación para revisarlo.';});
document.getElementById('privacy-button').addEventListener('click',()=>document.getElementById('privacy').showModal());
